/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }
public static ArrayList<String> classPassers(String[] students,int[] midtermGrades,int[] finalGrades,double midtermPercentage,double finalPercentage,double treshold){
    ArrayList<String> passedStudents = new ArrayList<String>();
    double midtermPoint=0;
    double finalPoint=0;
    double totalPoint=0;
    if(students==null){
        return null;
    }else if(midtermGrades==null){
        return null;
    }else if(finalGrades==null){
        return null;
    }
        for (int i = 0; i < students.length; i++) {
            midtermPoint=(midtermGrades[i]*midtermPercentage)/100;
            finalPoint=(finalGrades[i]*finalPercentage)/100;
            totalPoint=midtermPoint+finalPoint;
            if(totalPoint>=treshold){
                passedStudents.add(students[i]);
            }
        }
        if(passedStudents.isEmpty())
        passedStudents.add("no one passed");
    return passedStudents;
}
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
