/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test 

    public void testFirstTwo(){
        String[] students ={"dogukan","orkun", "yigit", "taylan"};
        int[] midtermGrades={100,90,20,10};
        int[] finalGrades={100,90,20,10};      
        ArrayList<String> array = new ArrayList<>(Arrays.asList("dogukan", "orkun"));
        assertEquals(App.classPassers(students,midtermGrades, finalGrades, 40, 60, 50),array);
    }

    @Test 

    public void testLastTwo(){
        String[] students ={"dogukan","orkun", "yigit", "taylan"};
        int[] midtermGrades={0,10,100,100};
        int[] finalGrades={40,10,50,50};      
        ArrayList<String> array = new ArrayList<>(Arrays.asList("yigit", "taylan"));
        assertEquals(App.classPassers(students,midtermGrades, finalGrades, 40, 60, 50),array);
    }

    @Test 

    public void testMidTwo(){
        String[] students ={"dogukan","orkun", "yigit", "taylan"};
        int[] midtermGrades={0,100,100,10};
        int[] finalGrades={40,100,70,20};      
        ArrayList<String> array = new ArrayList<>(Arrays.asList("orkun", "yigit"));
        assertEquals(App.classPassers(students,midtermGrades, finalGrades, 40, 60, 50),array);
    }


    @Test 

    public void testNone(){
        String[] students ={"dogukan","orkun", "yigit", "taylan"};
        int[] midtermGrades={0,10,20,10};
        int[] finalGrades={20,30,20,10};    
        ArrayList<String> array = new ArrayList<>(Arrays.asList("no one passed"));  
        assertEquals(App.classPassers(students,midtermGrades, finalGrades, 40, 60, 50),array);
    }
    
    @Test 

    public void testAll(){
        String[] students ={"dogukan","orkun", "yigit", "taylan"};
        int[] midtermGrades={100,100,90,80};
        int[] finalGrades={100,90,80,80};      
        ArrayList<String> array = new ArrayList<>(Arrays.asList("dogukan", "orkun","yigit","taylan"));
        assertEquals(App.classPassers(students,midtermGrades, finalGrades, 40, 60, 50),array);
    }

    @Test 

    public void testStudentsNull(){
        String[] students =null;
        int[] midtermGrades={100,100,90,80};
        int[] finalGrades={100,90,80,80};         
        assertNull(App.classPassers(students,midtermGrades, finalGrades, 40, 60, 50));
    } 

    @Test 

    public void testMidtermGradesNull(){
        String[] students ={"dogukan","orkun", "yigit", "taylan"};
        int[] midtermGrades=null;
        int[] finalGrades={100,90,80,80};  
        assertNull(App.classPassers(students,midtermGrades, finalGrades, 40, 60, 50));
    } 

    @Test 

    public void testFinalGradesNull(){
        String[] students ={"dogukan","orkun", "yigit", "taylan"};
        int[] midtermGrades={100,100,90,80};
        int[] finalGrades=null;      
        assertNull(App.classPassers(students,midtermGrades, finalGrades, 40, 60, 50));
    } 
}